### ISSUE TITLE
Are there releases?

### ISSUE THREAD

**Issue by slipher** [interstellar-oasis/interstellar-oasis#4]
Are there builds of the maps in this collection available to download anywhere?

**Comment by illwieckz** [comment]
Currently only the tremulous stock maps, RSMSE and the UT ones (Terminus and Area3) have been released.

**Comment by slipher** [comment]
Where are those releases published? Also if I have a pak for some map, is there an easy way to distinguish an InterstellarOasis port vs. one that was just repackaged from Tremulous or whatever?

**Comment by illwieckz** [comment]
> Where are those releases published?

Starting with 2023, I publish them there: https://github.com/InterstellarOasis/InterstellarOasis/releases

> Also if I have a pak for some map, is there an easy way to distinguish an InterstellarOasis port vs. one that was just repackaged from Tremulous or whatever?

The README of released InterstellarOasis ports mention InterstellarOasis.

Also, InterstellarOasis ports use Urcheon so they use lossless WebP lightmaps, and if there are textures, they are CRN ones.
